### ISSUE TITLE
DHCPv4 Options additions are not replicated from Origin to Replica

### ISSUE THREAD

**Issue by stlouey** [linuxserver/docker-adguardhome-sync#16]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Current State

Origin

dhcpv4:
options:
- 6 ips 10.0.0.20,10.0.0.21

Replica

dhcpv4:
options: []

Future Sate Example

Origin

dhcpv4:
options:
- 6 ips 10.0.0.20,10.0.0.21

Replica

dhcpv4:
options:
- 6 ips 10.0.0.20,10.0.0.21

### Reason for change

DNS High Availability (HA), one more thing towards full HA automation.

### Proposed code change

Include the dhcp.dhcpv4.options array field in sunc from origin to replica.

(https://github.com/AdguardTeam/AdGuardHome/wiki/DHCP#config-4)

**Comment by thespad** [comment]
This needs to be raised as a request for the upstream project: https://github.com/bakito/adguardhome-sync/
