### ISSUE TITLE
[BUG] FILE__ environment variables get added a \n

### ISSUE THREAD

**Issue by DennisGaida** [linuxserver/docker-adguardhome-sync#6]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to use the `FILE__` environment variables to make use of docker secrets.

E.g. using `FILE__ORIGIN_USERNAME: /run/secrets/myUser` and `myUser` being `foo`, adguardhome-sync receives `user\n` - the same goes for all other environment variables.

The environment variables of the original image are not listed as supported environment variables for this image, maybe they are not supposed to be used this way?

I suppose this is a [linuxserver](https://github.com/linuxserver/docker-adguardhome-sync) issue since `FILE__` comes directly from the base image. Using the environment variables without `FILE__` (e.g. `ORIGIN_USERNAME`) does work without issues.

### Expected Behavior

Environment variables with the `FILE__` prefix shouldn't get an extra newline `\n` added.

### Steps To Reproduce

1. Use image and set environment variable such as `FILE__ORIGIN_USERNAME: /run/secrets/myUser`
2. Make use of docker secrets to fill that referenced file or make use of volume mounts
3. Observe the log (`LOG_LEVEL: debug`) for environment variable
4. See that all variables being passed with `FILE__` get a newline `\n` suffix.

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

arm64

### Docker creation

```bash
adguard-sync:
    image: lscr.io/linuxserver/adguardhome-sync:latest
    container_name: adguard-sync
    environment:
      ORIGIN_URL: ${ADGUARD_ORIGIN_SERVER}
      FILE__ORIGIN_USERNAME: /run/secrets/myUser
      FILE__ORIGIN_PASSWORD: /run/secrets/myPassword
      REPLICA_URL: ${ADGUARD_REPLICA_SERVER}
      FILE__REPLICA_USERNAME: /run/secrets/myUser
      FILE__REPLICA_PASSWORD: /run/secrets/myPassword
      LOG_LEVEL: debug
      # REPLICA1_AUTOSETUP: true # if true, AdGuardHome is automatically initialized.
      CRON: '*/10 * * * *' # run every 10 minutes
      RUNONSTART: true
      # Configure sync features; by default all features are enabled.
      # FEATURES_GENERALSETTINGS: true
      # FEATURES_QUERYLOGCONFIG: true
      # FEATURES_STATSCONFIG: true
      # FEATURES_CLIENTSETTINGS: true
      # FEATURES_SERVICES: true
      # FEATURES_FILTERS: true
      # FEATURES_DHCP_SERVERCONFIG: true
      # FEATURES_DHCP_STATICLEASES: true
      # FEATURES_DNS_SERVERCONFIG: true
      # FEATURES_DNS_ACCESSLISTS: true
      # FEATURES_DNS_REWRITES: true
    volumes:
      - ./adguard-sync:/config
    secrets:
      - myUser
      - myPassword
```

### Container logs

```bash
2023-01-30T00:48:53.785+0100    DEBUG   client  client/client.go:155    got response    {"host": "192.168.178.178:8099", "method": "GET", "path": "status", "username": "myUser\n", "status": 403, "body": "Forbidden", "content-type": ["text/plain; charset=utf-8"]}
```
```

**Comment by Roxedus** [comment]
We do not add a newline, we inject the content of the file untouched. Both vi(m) and nano automatically adds a trailing newline. `cat -e` would make it more apparent to view.

**Comment by Roxedus** [comment]
You can also pass -n to echo :) https://linux.die.net/man/1/echo

**Comment by aptalca** [comment]
We don't mess with the value users set as we wouldn't know whether the line break is supposed to be part of the var or not.

Docker docs recommend using `printf` to create secrets
